// DO NOT EDIT THIS FILE
use crate::solver::{ProblemOutput, Solver};

mod day01;


pub fn exec_day(day: u32) -> Option<ProblemOutput> {
    match day {
        1 => Some(day01::Problem.solve(day)),
        _ => None,
    }
}

pub fn exec_all_days() -> Vec<ProblemOutput> {
    vec![
        day01::Problem.solve(1),
    ]
}
